name: Test

on:
  pull_request

jobs:
  build:
    strategy:
      matrix:
        node-version: [12, 14, 16, 18]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
      - uses: actions/checkout@v3

      - name: Setup node
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
      - run: npm i --ignore-scripts

      - name: Run tests
      - run: npm test
